<?php

namespace Database\Seeders;

use App\Models\BlogPost;
use Illuminate\Database\Seeder;

class BlogPostSeeder extends Seeder
{
    public function run(): void
    {
        BlogPost::insert([
            ['id' => 1, 'slug' => '5-signs-heart-attack-women', 'title' => '5 subtle signs of a heart attack in women', 'excerpt' => 'Heart disease presents differently in women. Here are the warning signs to know.', 'content' => "Heart disease is the leading cause of death for women worldwide, yet symptoms are often dismissed or misattributed.\n\nMany women experience warning signs weeks before a heart attack. Recognizing these early signals can save lives.\n\n## 1. Unexplained fatigue\n\nUnusual, persistent fatigue that interferes with daily activities is one of the most commonly reported pre-heart-attack symptoms in women.\n\n## 2. Shortness of breath\n\nIf climbing stairs or walking short distances leaves you winded when it didn't before, take note. This can occur without chest discomfort.\n\n## 3. Indigestion or nausea\n\nMany women mistake heart attack symptoms for acid reflux or the flu. Pressure or pain in the upper abdomen is a red flag.\n\n## 4. Jaw or neck pain\n\nRather than classic chest pain, women often report discomfort in the jaw, neck, or upper back that comes and goes.\n\n## 5. Cold sweat or dizziness\n\nBreaking out in a cold sweat or feeling lightheaded without a clear cause warrants immediate medical attention.\n\nIf you experience any combination of these symptoms, call emergency services right away.", 'category' => 'Cardiology', 'author' => 'Dr. Sarah Chen', 'author_id' => 1, 'published_at' => '2026-05-14 00:00:00', 'read_minutes' => 6, 'image' => 'https://images.unsplash.com/photo-1559757175-5700dde675bc?auto=format&fit=crop&w=1200&q=80', 'tags' => json_encode(['Heart Health', "Women's Health"])],
            ['id' => 2, 'slug' => 'managing-diabetes-monsoon', 'title' => 'Managing diabetes during monsoon season', 'excerpt' => 'Practical guidance for blood sugar stability when the weather changes.', 'content' => "Monsoon season brings unique challenges for people living with diabetes.\n\nFrom foot care during waterlogging to maintaining a steady diet when comfort food beckons, a few adjustments can keep your blood sugar stable.\n\n## Foot care is critical\n\nWet feet can lead to fungal infections, which are especially dangerous for diabetic patients. Always dry your feet thoroughly and inspect for cuts daily.\n\n## Watch your diet\n\nIt's tempting to reach for fried snacks during rainy weather. Opt for steamed options and keep your meal timing consistent.\n\n## Stay active indoors\n\nDon't let rain derail your exercise routine. Indoor yoga, stretching, or a stationary bike can maintain your activity levels.\n\n## Monitor more frequently\n\nHumidity and temperature changes can affect insulin absorption. Check your blood sugar levels more often during monsoon months.", 'category' => 'Wellness', 'author' => 'Dr. James Wilson', 'author_id' => 2, 'published_at' => '2026-06-02 00:00:00', 'read_minutes' => 5, 'image' => 'https://images.unsplash.com/photo-1551076805-e1869033e561?auto=format&fit=crop&w=1200&q=80', 'tags' => json_encode(['Diabetes', 'Lifestyle'])],
            ['id' => 3, 'slug' => 'robotic-surgery-explained', 'title' => 'Robotic surgery, explained simply', 'excerpt' => 'What the surgeon controls, what the robot does, and what it means for recovery.', 'content' => "Robot-assisted surgery is one of the most misunderstood advancements in modern medicine.\n\nDespite the name, the surgeon is always in complete control. The robot is an extension of the surgeon's hands — a sophisticated tool that enhances precision.\n\n## How it works\n\nThe surgeon sits at a console and controls robotic arms that hold surgical instruments. A high-definition 3D camera provides magnified, immersive views of the operating site.\n\n## Benefits for patients\n\n- Smaller incisions — often just 1–2 cm\n- Less blood loss\n- Reduced pain and scarring\n- Shorter hospital stays\n- Faster return to normal activities\n\n## Is it right for you?\n\nRobotic surgery is ideal for many procedures including prostate surgery, hysterectomy, heart valve repair, and bariatric surgery.\n\nTalk to your surgeon about whether robotic-assisted techniques are appropriate for your specific condition.", 'category' => 'Innovation', 'author' => 'Dr. Marcus Thorne', 'author_id' => 3, 'published_at' => '2026-06-10 00:00:00', 'read_minutes' => 8, 'image' => 'https://images.unsplash.com/photo-1631815589968-fdb09a223b1e?auto=format&fit=crop&w=1200&q=80', 'tags' => json_encode(['Surgery', 'Technology'])],
            ['id' => 4, 'slug' => 'pediatric-vaccination-schedule', 'title' => 'Updated pediatric vaccination schedule for 2026', 'excerpt' => "What's new this year and how to keep your child on track.", 'content' => "Vaccination schedules are updated yearly to reflect the latest medical evidence.\n\nHere are the key changes for 2026 and what every parent should discuss at their child's next checkup.\n\n## New recommendations for 2026\n\nThe CDC and WHO have updated guidelines for several vaccines. The most notable changes include:\n\n- RSV vaccine now recommended for all infants under 8 months\n- HPV vaccine series reduced from 3 doses to 2 for adolescents under 15\n- COVID-19 boosters added to the standard immunization schedule for children 6 months and older\n\n## Keeping on track\n\nMissed a vaccination? Don't panic. Your pediatrician can create a catch-up schedule tailored to your child's age and health status.\n\n## Common questions\n\n**Are vaccines safe?** Yes. Extensive clinical trials and ongoing monitoring ensure vaccine safety.\n\n**Can my child get multiple vaccines at once?** Absolutely. Combination vaccines are extensively tested and reduce the number of office visits.", 'category' => 'Pediatrics', 'author' => 'Dr. Amara Okafor', 'author_id' => 4, 'published_at' => '2026-05-28 00:00:00', 'read_minutes' => 4, 'image' => 'https://images.unsplash.com/photo-1581056771107-24ca5f033842?auto=format&fit=crop&w=1200&q=80', 'tags' => json_encode(['Pediatrics', 'Vaccines'])],
        ]);
    }
}
