<?php

namespace Database\Seeders;

use App\Models\Doctor;
use Illuminate\Database\Seeder;

class DoctorSeeder extends Seeder
{
    public function run(): void
    {
        Doctor::insert([
            ['slug' => 'sarah-chen', 'name' => 'Dr. Sarah Chen', 'designation' => 'Senior Interventional Cardiologist', 'department_slug' => 'cardiology', 'department' => 'Cardiology', 'qualifications' => json_encode(['MD, Harvard Medical School', 'Fellowship, Mayo Clinic']), 'experience_years' => 18, 'languages' => json_encode(['English', 'Mandarin']), 'photo' => 'https://images.unsplash.com/photo-1559839734-2b71ea197ec2?auto=format&fit=crop&w=600&q=80', 'bio' => 'Dr. Chen specializes in complex coronary interventions and structural heart disease, having performed over 4,000 catheterization procedures.', 'expertise' => json_encode(['Angioplasty', 'TAVR', 'Complex PCI', 'Structural Heart']), 'schedule' => json_encode([['day' => 'Mon–Wed', 'hours' => '9:00 AM – 1:00 PM'], ['day' => 'Fri', 'hours' => '2:00 PM – 6:00 PM']]), 'publications' => json_encode(['NEJM 2023 — Outcomes in High-Risk PCI', 'JACC 2022 — Structural Heart Review'])],
            ['slug' => 'marcus-thorne', 'name' => 'Dr. Marcus Thorne', 'designation' => 'Director, Neurosurgery', 'department_slug' => 'neurology', 'department' => 'Neurology', 'qualifications' => json_encode(['MBBS, Stanford', 'Neurosurgery Residency, Johns Hopkins']), 'experience_years' => 22, 'languages' => json_encode(['English', 'French']), 'photo' => 'https://images.unsplash.com/photo-1612349317150-e413f6a5b16d?auto=format&fit=crop&w=600&q=80', 'bio' => 'Internationally recognized expert in robotic-assisted spine surgery and complex skull-base procedures.', 'expertise' => json_encode(['Spine Surgery', 'Brain Tumors', 'Robotic Surgery']), 'schedule' => json_encode([['day' => 'Tue, Thu', 'hours' => '10:00 AM – 2:00 PM']]), 'publications' => json_encode([])],
            ['slug' => 'elena-rodriguez', 'name' => 'Dr. Elena Rodriguez', 'designation' => 'Chief, Medical Oncology', 'department_slug' => 'oncology', 'department' => 'Oncology', 'qualifications' => json_encode(['MD, Johns Hopkins', 'Fellowship, MSKCC']), 'experience_years' => 16, 'languages' => json_encode(['English', 'Spanish']), 'photo' => 'https://images.unsplash.com/photo-1594824476967-48c8b964273f?auto=format&fit=crop&w=600&q=80', 'bio' => 'Pioneer in immunotherapy protocols for breast and gastrointestinal cancers, with a focus on personalized care.', 'expertise' => json_encode(['Breast Cancer', 'GI Cancers', 'Immunotherapy']), 'schedule' => json_encode([['day' => 'Mon–Fri', 'hours' => '9:00 AM – 1:00 PM']]), 'publications' => json_encode([])],
            ['slug' => 'james-wilson', 'name' => 'Dr. James Wilson', 'designation' => 'Senior Cardiologist', 'department_slug' => 'cardiology', 'department' => 'Cardiology', 'qualifications' => json_encode(['MD, Mayo Clinic', 'DM Cardiology']), 'experience_years' => 24, 'languages' => json_encode(['English']), 'photo' => 'https://images.unsplash.com/photo-1622253692010-333f2da6031d?auto=format&fit=crop&w=600&q=80', 'bio' => 'Recognized for non-invasive cardiology and preventative heart programs with thousands of long-term patients.', 'expertise' => json_encode(['Echocardiography', 'Preventive Cardiology', 'Heart Failure']), 'schedule' => json_encode([['day' => 'Mon, Wed, Fri', 'hours' => '10:00 AM – 4:00 PM']]), 'publications' => json_encode([])],
            ['slug' => 'amara-okafor', 'name' => 'Dr. Amara Okafor', 'designation' => 'Consultant, Pediatric Neurology', 'department_slug' => 'pediatrics', 'department' => 'Pediatrics', 'qualifications' => json_encode(['MD, University College London']), 'experience_years' => 12, 'languages' => json_encode(['English', 'French']), 'photo' => 'https://images.unsplash.com/photo-1551601651-2a8555f1a136?auto=format&fit=crop&w=600&q=80', 'bio' => 'Specialist in pediatric epilepsy, neuro-developmental disorders, and complex care coordination.', 'expertise' => json_encode(['Pediatric Epilepsy', 'Developmental Disorders']), 'schedule' => json_encode([['day' => 'Tue, Thu, Sat', 'hours' => '9:00 AM – 1:00 PM']]), 'publications' => json_encode([])],
            ['slug' => 'rohan-mehta', 'name' => 'Dr. Rohan Mehta', 'designation' => 'Senior Orthopedic Surgeon', 'department_slug' => 'orthopedics', 'department' => 'Orthopedics', 'qualifications' => json_encode(['MS Ortho, AIIMS', 'Fellowship, Mass General']), 'experience_years' => 19, 'languages' => json_encode(['English', 'Hindi']), 'photo' => 'https://images.unsplash.com/photo-1537368910025-700350fe46c7?auto=format&fit=crop&w=600&q=80', 'bio' => 'Joint reconstruction expert performing over 500 robot-assisted knee replacements annually.', 'expertise' => json_encode(['Robotic Knee Surgery', 'Sports Injuries', 'Hip Replacement']), 'schedule' => json_encode([['day' => 'Mon–Fri', 'hours' => '11:00 AM – 5:00 PM']]), 'publications' => json_encode([])],
            ['slug' => 'priya-sharma', 'name' => 'Dr. Priya Sharma', 'designation' => 'Consultant Gastroenterologist', 'department_slug' => 'gastroenterology', 'department' => 'Gastroenterology', 'qualifications' => json_encode(['MD, AIIMS', 'DM Gastroenterology, PGIMER']), 'experience_years' => 14, 'languages' => json_encode(['English', 'Hindi', 'Punjabi']), 'photo' => 'https://images.unsplash.com/photo-1594824476967-48c8b964273f?auto=format&fit=crop&w=600&q=80', 'bio' => 'Specialist in therapeutic endoscopy and hepatology with expertise in managing complex GI disorders and liver diseases.', 'expertise' => json_encode(['Therapeutic Endoscopy', 'Hepatology', 'IBD Management', 'ERCP']), 'schedule' => json_encode([['day' => 'Mon, Wed, Fri', 'hours' => '9:00 AM – 3:00 PM']]), 'publications' => json_encode([])],
            ['slug' => 'michael-park', 'name' => 'Dr. Michael Park', 'designation' => 'Chief of Ophthalmology', 'department_slug' => 'ophthalmology', 'department' => 'Ophthalmology', 'qualifications' => json_encode(['MD, University of Toronto', 'Fellowship, Wilmer Eye Institute']), 'experience_years' => 20, 'languages' => json_encode(['English', 'Korean']), 'photo' => 'https://images.unsplash.com/photo-1612349317150-e413f6a5b16d?auto=format&fit=crop&w=600&q=80', 'bio' => 'Renowned for advanced cataract and refractive surgery, with over 10,000 successful LASIK and phacoemulsification procedures.', 'expertise' => json_encode(['Cataract Surgery', 'LASIK', 'Glaucoma', 'Retinal Disorders']), 'schedule' => json_encode([['day' => 'Tue–Sat', 'hours' => '10:00 AM – 4:00 PM']]), 'publications' => json_encode(['J Cataract Refract Surg 2022 — FLACS outcomes'])],
            ['slug' => 'lisa-patel', 'name' => 'Dr. Lisa Patel', 'designation' => 'Senior Dermatologist', 'department_slug' => 'dermatology', 'department' => 'Dermatology', 'qualifications' => json_encode(['MD, University of Chicago', 'Residency, Stanford']), 'experience_years' => 13, 'languages' => json_encode(['English', 'Gujarati']), 'photo' => 'https://images.unsplash.com/photo-1559839734-2b71ea197ec2?auto=format&fit=crop&w=600&q=80', 'bio' => 'Expert in medical and cosmetic dermatology, specializing in skin cancer detection, laser therapy, and aesthetic rejuvenation.', 'expertise' => json_encode(['Skin Cancer Surgery', 'Laser Therapy', 'Botulinum Toxin', 'Psoriasis Treatment']), 'schedule' => json_encode([['day' => 'Mon–Thu', 'hours' => '9:00 AM – 5:00 PM']]), 'publications' => json_encode([])],
            ['slug' => 'ahmed-hassan', 'name' => 'Dr. Ahmed Hassan', 'designation' => 'Pulmonologist & Critical Care Specialist', 'department_slug' => 'pulmonology', 'department' => 'Pulmonology', 'qualifications' => json_encode(['MBBS, Cairo University', 'MD Pulmonary, Johns Hopkins']), 'experience_years' => 17, 'languages' => json_encode(['English', 'Arabic', 'French']), 'photo' => 'https://images.unsplash.com/photo-1537368910025-700350fe46c7?auto=format&fit=crop&w=600&q=80', 'bio' => 'Leading expert in interventional pulmonology and sleep medicine, with extensive ICU management experience.', 'expertise' => json_encode(['Bronchoscopy', 'Sleep Medicine', 'Mechanical Ventilation', 'Interstitial Lung Disease']), 'schedule' => json_encode([['day' => 'Sun–Thu', 'hours' => '8:00 AM – 2:00 PM']]), 'publications' => json_encode([])],
            ['slug' => 'sophie-martin', 'name' => 'Dr. Sophie Martin', 'designation' => 'Nephrologist & Hypertension Specialist', 'department_slug' => 'nephrology', 'department' => 'Nephrology', 'qualifications' => json_encode(['MD, Université Paris Descartes', 'Fellowship, Cleveland Clinic']), 'experience_years' => 15, 'languages' => json_encode(['English', 'French', 'German']), 'photo' => 'https://images.unsplash.com/photo-1594824476967-48c8b964273f?auto=format&fit=crop&w=600&q=80', 'bio' => 'Specializes in chronic kidney disease management, dialysis access, and post-transplant care with a patient-centered approach.', 'expertise' => json_encode(['CKD Management', 'Hemodialysis', 'Kidney Transplant', 'Hypertension']), 'schedule' => json_encode([['day' => 'Mon–Fri', 'hours' => '9:00 AM – 1:00 PM']]), 'publications' => json_encode(['KI Reports 2023 — Novel biomarkers in AKI'])],
            ['slug' => 'david-kim', 'name' => 'Dr. David Kim', 'designation' => 'Endocrinologist & Diabetes Specialist', 'department_slug' => 'endocrinology', 'department' => 'Endocrinology', 'qualifications' => json_encode(['MD, UCLA', 'Fellowship, Joslin Diabetes Center']), 'experience_years' => 11, 'languages' => json_encode(['English', 'Korean', 'Spanish']), 'photo' => 'https://images.unsplash.com/photo-1612349317150-e413f6a5b16d?auto=format&fit=crop&w=600&q=80', 'bio' => 'Passionate about managing diabetes, thyroid disorders, and metabolic diseases through evidence-based medicine and lifestyle intervention.', 'expertise' => json_encode(['Diabetes Management', 'Thyroid Disorders', 'Osteoporosis', 'Pituitary Disorders']), 'schedule' => json_encode([['day' => 'Mon–Thu', 'hours' => '8:00 AM – 4:00 PM']]), 'publications' => json_encode([])],
            ['slug' => 'fatima-ali', 'name' => 'Dr. Fatima Ali', 'designation' => 'Consultant Urologist', 'department_slug' => 'urology', 'department' => 'Urology', 'qualifications' => json_encode(['MBBS, Karachi University', 'FRCS Urology, Royal College of Surgeons']), 'experience_years' => 21, 'languages' => json_encode(['English', 'Urdu', 'Punjabi']), 'photo' => 'https://images.unsplash.com/photo-1559839734-2b71ea197ec2?auto=format&fit=crop&w=600&q=80', 'bio' => 'Highly experienced urological surgeon specializing in minimally invasive procedures for prostate, kidney, and bladder conditions.', 'expertise' => json_encode(['Laparoscopic Surgery', 'Prostate Disorders', 'Kidney Stones', 'Uro-Oncology']), 'schedule' => json_encode([['day' => 'Mon–Fri', 'hours' => '10:00 AM – 3:00 PM']]), 'publications' => json_encode(['J Urol 2021 — HoLEP outcomes'])],
            ['slug' => 'thomas-mueller', 'name' => 'Dr. Thomas Mueller', 'designation' => 'Chief of Anesthesiology', 'department_slug' => 'anesthesiology', 'department' => 'Anesthesiology', 'qualifications' => json_encode(['MD, Charité Berlin', 'Fellowship, Mayo Clinic']), 'experience_years' => 25, 'languages' => json_encode(['English', 'German', 'Italian']), 'photo' => 'https://images.unsplash.com/photo-1622253692010-333f2da6031d?auto=format&fit=crop&w=600&q=80', 'bio' => 'Leading anesthesiologist with expertise in cardiac anesthesia, pain management, and perioperative patient safety protocols.', 'expertise' => json_encode(['Cardiac Anesthesia', 'Pain Management', 'Critical Care', 'Regional Anesthesia']), 'schedule' => json_encode([['day' => 'Mon–Sat', 'hours' => 'On-call rotation']]), 'publications' => json_encode(['Anesthesiology 2022 — ERAS protocol meta-analysis'])],
            ['slug' => 'nina-thompson', 'name' => 'Dr. Nina Thompson', 'designation' => 'Internal Medicine Specialist', 'department_slug' => 'internal-medicine', 'department' => 'Internal Medicine', 'qualifications' => json_encode(['MD, University of Melbourne', 'FRACP']), 'experience_years' => 10, 'languages' => json_encode(['English', 'Mandarin']), 'photo' => 'https://images.unsplash.com/photo-1594824476967-48c8b964273f?auto=format&fit=crop&w=600&q=80', 'bio' => 'Dedicated internal medicine physician focused on comprehensive adult primary care, preventive health, and managing complex multimorbidity.', 'expertise' => json_encode(['Preventive Medicine', 'Chronic Disease Management', 'Infectious Diseases', 'Geriatric Care']), 'schedule' => json_encode([['day' => 'Mon–Fri', 'hours' => '8:00 AM – 5:00 PM']]), 'publications' => json_encode([])],
        ]);
    }
}
