<?php

namespace Database\Seeders;

use App\Models\JobOpening;
use Illuminate\Database\Seeder;

class JobOpeningSeeder extends Seeder
{
    public function run(): void
    {
        JobOpening::insert([
            [
                'title' => 'Senior Cardiologist',
                'slug' => 'senior-cardiologist',
                'location' => 'Kathmandu, Nepal',
                'type' => 'full-time',
                'category' => 'clinical',
                'department' => 'Cardiology',
                'salary_range' => 'Negotiable',
                'description' => 'We are seeking an experienced Senior Cardiologist to join our world-class cardiology department. The ideal candidate will have extensive experience in interventional cardiology and a passion for patient-centered care.',
                'requirements' => "- DM in Cardiology from a recognized institution\n- Minimum 5 years of post-specialization experience\n- Proven track record in interventional procedures\n- Excellent communication and leadership skills",
                'benefits' => "- Competitive salary package\n- Health insurance for self and family\n- CME allowance and study leave\n- State-of-the-art Cath Lab access",
                'application_url' => null,
                'closing_date' => null,
                'is_active' => true,
                'order' => 1,
            ],
            [
                'title' => 'Staff Nurse — ICU',
                'slug' => 'staff-nurse-icu',
                'location' => 'Kathmandu, Nepal',
                'type' => 'full-time',
                'category' => 'clinical',
                'department' => 'Nursing',
                'salary_range' => 'NRs. 45,000 – 65,000/month',
                'description' => 'Join our intensive care nursing team and provide critical care to patients in our state-of-the-art 40-bed ICU. We offer a supportive environment with continuous learning opportunities.',
                'requirements' => "- B.Sc. Nursing or equivalent\n- Valid Nepal Nursing Council registration\n- Minimum 2 years ICU experience preferred\n- BLS/ACLS certification is a plus",
                'benefits' => "- Shift allowances and overtime pay\n- Accommodation assistance\n- Professional development programs\n- Wellness programs",
                'application_url' => null,
                'closing_date' => '2026-08-31',
                'is_active' => true,
                'order' => 2,
            ],
            [
                'title' => 'Radiology Technician',
                'slug' => 'radiology-technician',
                'location' => 'Kathmandu, Nepal',
                'type' => 'full-time',
                'category' => 'allied-health',
                'department' => 'Radiology',
                'salary_range' => 'NRs. 35,000 – 50,000/month',
                'description' => 'We are looking for skilled Radiology Technicians to operate our advanced imaging equipment including 3T MRI, 256-slice CT, and digital X-ray systems.',
                'requirements' => "- Diploma or Degree in Radiography/Medical Imaging\n- Minimum 1 year experience in a hospital setting\n- Proficiency in MRI and CT modalities preferred",
                'benefits' => "- Competitive salary with annual increments\n- On-site cafeteria and transport\n- Uniforms provided",
                'application_url' => null,
                'closing_date' => null,
                'is_active' => true,
                'order' => 3,
            ],
            [
                'title' => 'Medical Lab Technologist',
                'slug' => 'medical-lab-technologist',
                'location' => 'Kathmandu, Nepal',
                'type' => 'full-time',
                'category' => 'allied-health',
                'department' => 'Laboratory',
                'salary_range' => 'NRs. 30,000 – 45,000/month',
                'description' => 'Join our NABL-accredited laboratory team. We handle a high volume of routine and specialized tests with state-of-the-art automated analyzers.',
                'requirements' => "- B.Sc. in Medical Laboratory Technology\n- Registration with relevant council\n- Attention to detail and quality-focused mindset",
                'benefits' => "- Shift allowances\n- Health insurance\n- Opportunity to work with advanced diagnostic equipment",
                'application_url' => null,
                'closing_date' => '2026-09-15',
                'is_active' => true,
                'order' => 4,
            ],
            [
                'title' => 'Hospital Administrator',
                'slug' => 'hospital-administrator',
                'location' => 'Kathmandu, Nepal',
                'type' => 'full-time',
                'category' => 'administration',
                'department' => 'Administration',
                'salary_range' => 'Negotiable',
                'description' => 'We seek an experienced Hospital Administrator to oversee daily operations, ensure regulatory compliance, and drive operational excellence across departments.',
                'requirements' => "- MHA or MBA in Healthcare Management\n- Minimum 7 years experience in hospital administration\n- Strong leadership and problem-solving skills\n- Knowledge of NHRC and hospital accreditation standards",
                'benefits' => "- Executive-level compensation\n- Performance bonuses\n- Vehicle allowance\n- Leadership development programs",
                'application_url' => null,
                'closing_date' => null,
                'is_active' => true,
                'order' => 5,
            ],
            [
                'title' => 'IT Support Engineer',
                'slug' => 'it-support-engineer',
                'location' => 'Kathmandu, Nepal',
                'type' => 'full-time',
                'category' => 'technical',
                'department' => 'IT',
                'salary_range' => 'NRs. 40,000 – 60,000/month',
                'description' => 'We are looking for an IT Support Engineer to maintain our hospital information systems, troubleshoot hardware/software issues, and ensure smooth IT operations across the facility.',
                'requirements' => "- Bachelor's degree in IT/Computer Science\n- Experience with HIS (Hospital Information Systems)\n- Knowledge of networking and server management\n- 2+ years of relevant experience",
                'benefits' => "- Professional certification support\n- Flexible working hours\n- Modern IT infrastructure to work with",
                'application_url' => null,
                'closing_date' => '2026-07-30',
                'is_active' => true,
                'order' => 6,
            ],
            [
                'title' => 'Physiotherapist',
                'slug' => 'physiotherapist',
                'location' => 'Kathmandu, Nepal',
                'type' => 'part-time',
                'category' => 'allied-health',
                'department' => 'Rehabilitation',
                'salary_range' => 'NRs. 500 – 800/hour',
                'description' => 'We are hiring a part-time Physiotherapist for our rehabilitation department. Services include post-surgical rehab, sports injury management, and geriatric care.',
                'requirements' => "- BPT/MPT from a recognized university\n- Nepal Health Professional Council registration\n- Experience in orthopaedic and neurological rehab preferred",
                'benefits' => "- Flexible scheduling\n- Access to modern gym equipment\n- Opportunity to work with diverse patient cases",
                'application_url' => null,
                'closing_date' => null,
                'is_active' => true,
                'order' => 7,
            ],
            [
                'title' => 'Marketing & Communications Officer',
                'slug' => 'marketing-communications-officer',
                'location' => 'Kathmandu, Nepal',
                'type' => 'full-time',
                'category' => 'administration',
                'department' => 'Marketing',
                'salary_range' => 'NRs. 50,000 – 70,000/month',
                'description' => 'We seek a creative Marketing & Communications Officer to enhance our brand presence, manage social media, coordinate events, and produce patient education content.',
                'requirements' => "- Bachelor's degree in Marketing, Communications, or related field\n- 3+ years experience in digital marketing\n- Excellent writing and content creation skills\n- Experience with SEO, social media management, and analytics",
                'benefits' => "- Creative work environment\n- Performance-based incentives\n- Professional development opportunities",
                'application_url' => null,
                'closing_date' => '2026-08-15',
                'is_active' => true,
                'order' => 8,
            ],
            [
                'title' => 'Pharmacist',
                'slug' => 'pharmacist',
                'location' => 'Kathmandu, Nepal',
                'type' => 'full-time',
                'category' => 'allied-health',
                'department' => 'Pharmacy',
                'salary_range' => 'NRs. 35,000 – 55,000/month',
                'description' => 'Join our 24-hour in-house pharmacy team. Responsibilities include dispensing medications, patient counseling, inventory management, and ensuring compliance with regulations.',
                'requirements' => "- Bachelor's in Pharmacy\n- Nepal Pharmacy Council registration\n- Minimum 1 year experience in hospital pharmacy\n- Knowledge of drug interactions and inventory systems",
                'benefits' => "- Shift differentials\n- Health insurance\n- Continuing education support",
                'application_url' => null,
                'closing_date' => null,
                'is_active' => true,
                'order' => 9,
            ],
            [
                'title' => 'Housekeeping Supervisor',
                'slug' => 'housekeeping-supervisor',
                'location' => 'Kathmandu, Nepal',
                'type' => 'full-time',
                'category' => 'support',
                'department' => 'Facilities',
                'salary_range' => 'NRs. 25,000 – 35,000/month',
                'description' => 'Oversee the housekeeping team to maintain the highest standards of cleanliness and infection control across all hospital areas.',
                'requirements' => "- Minimum 2 years experience in housekeeping supervision\n- Knowledge of infection control protocols\n- Strong team management skills",
                'benefits' => "- Accommodation facility\n- Meal allowance\n- Uniforms and safety gear provided",
                'application_url' => null,
                'closing_date' => null,
                'is_active' => true,
                'order' => 10,
            ],
            [
                'title' => 'Dietitian / Nutritionist',
                'slug' => 'dietitian-nutritionist',
                'location' => 'Kathmandu, Nepal',
                'type' => 'full-time',
                'category' => 'allied-health',
                'department' => 'Dietetics',
                'salary_range' => 'NRs. 40,000 – 55,000/month',
                'description' => 'We are seeking a clinical Dietitian to provide medical nutrition therapy for inpatients and outpatients, develop dietary plans, and conduct wellness workshops.',
                'requirements' => "- MSc in Food & Nutrition or Clinical Dietetics\n- Registered Dietitian certification\n- Experience in a clinical setting preferred",
                'benefits' => "- Health insurance\n- Flexible schedule\n- Opportunity to run wellness programs",
                'application_url' => null,
                'closing_date' => '2026-08-31',
                'is_active' => true,
                'order' => 11,
            ],
            [
                'title' => 'Medical Records Officer',
                'slug' => 'medical-records-officer',
                'location' => 'Kathmandu, Nepal',
                'type' => 'full-time',
                'category' => 'administration',
                'department' => 'Medical Records',
                'salary_range' => 'NRs. 25,000 – 35,000/month',
                'description' => 'Manage and maintain patient medical records in compliance with legal and regulatory standards. Ensure accurate documentation, filing, and retrieval of records.',
                'requirements' => "- Bachelor's degree in Health Information Management or related field\n- Knowledge of medical terminology and coding\n- Proficiency in HMIS software",
                'benefits' => "- Health insurance\n- Annual leave and sick leave\n- Training opportunities",
                'application_url' => null,
                'closing_date' => null,
                'is_active' => true,
                'order' => 12,
            ],
        ]);
    }
}
